warp_denoising_step: false
weight_decay: 0.01
same_step_across_blocks: true
discriminator_lr_multiplier: 1.0
last_step_only: false
i2v: false
num_training_frames: 21
gc_interval: 100
context_noise: 0
causal: true

generator_config_path: wan_models/Wan2.1-T2V-1.3B/
real_score_config_path: wan_models/Wan2.1-T2V-14B/
real_score_checkpoint_path: wan_models/Wan2.1-T2V-14B/
fake_score_config_path: wan_models/Wan2.1-T2V-14B/
fake_score_checkpoint_path: wan_models/Wan2.1-T2V-14B/
text_encoder_checkpoint_path: wan_models/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth
vae_checkpoint_path: wan_models/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth

ckpt_step: 0
prompt_name: MovieGenVideoBench
prompt_path: prompts/MovieGenVideoBench.txt
eval_first_n: 64
num_samples: 1
height: 480
width: 832
num_frames: 81

no_save: false
no_visualize: false
vae_offload_cpu: true
logdir: logs
logging_level: info
disable_wandb: true

max_checkpoints: 2
total_training_steps: 600
inference_interval: 200
num_inference_prompts: 4

# Recommended: prevent Hydra from chdir into run dir (optional but common)
hydra:
  job:
    chdir: false
